# src/agents/feedback_memory_agents.py

import os
import json
from typing import Dict, Any
from src.agents.base_agent import BaseAgent


class FeedbackMemoryAgent(BaseAgent):
    """
    Stores knowledge gaps into persistent system_state.json
    using gap_signal generated by KnowledgeGapAgent.
    """

    def __init__(self, state_path="system_state.json"):
        self.state_path = state_path

    # ----------------------------------------------------------
    # Routing condition
    # ----------------------------------------------------------
    def can_handle(self, payload: dict) -> bool:
        return (
            payload.get("gap_signal") is not None
            and not payload.get("_feedback_done", False)
        )

    # ----------------------------------------------------------
    # Main execution
    # ----------------------------------------------------------
    def run(self, payload: dict) -> dict:

        gap_signal = payload.get("gap_signal")
        if not gap_signal:
            payload["_feedback_done"] = True
            return payload

        print("\n🧠 [FeedbackMemoryAgent] Logging knowledge gap...")

        query = payload.get("query")
        answer = payload.get("answer")  # may be None at this stage

        # 🔥 EXACT REQUIRED STRUCTURE
        gap_entry = {
            "question": query,
            "system_answer": answer.get("text") if answer else None,
            "gap_reason": gap_signal.get("reason"),
            "severity": gap_signal.get("severity"),
            "llm_analysis": gap_signal.get("llm_analysis", {})
        }

        # Update payload memory
        payload.setdefault("knowledge_gaps", [])
        payload["knowledge_gaps"].append(gap_entry)

        # Persist safely
        self._persist_to_system_state(payload["knowledge_gaps"])

        print("✅ Knowledge gap added to payload memory")

        # 🔥 CRITICAL: prevent loop
        payload["_feedback_done"] = True

        return payload

    # ----------------------------------------------------------
    # Persistence
    # ----------------------------------------------------------
    def _load_system_state(self) -> Dict[str, Any]:
        if not os.path.exists(self.state_path):
            return {"knowledge_gaps": [], "active_vector_source": "COSMOS"}

        try:
            state = json.loads(open(self.state_path).read())
            state.setdefault("knowledge_gaps", [])
            state.setdefault("active_vector_source", "COSMOS")
            return state
        except Exception:
            return {"knowledge_gaps": [], "active_vector_source": "COSMOS"}

    def _save_system_state(self, state: Dict[str, Any]):
        with open(self.state_path, "w") as f:
            json.dump(state, f, indent=2)

    def _persist_to_system_state(self, knowledge_gaps: list):

        state = self._load_system_state()

        state["knowledge_gaps"] = knowledge_gaps

        self._save_system_state(state)
        print("✅ Knowledge gaps persisted to system_state.json")