# src/agents/feedback_memory_agents.py

import os
import json
from typing import Dict, Any, Optional
from src.agents.base_agent import BaseAgent


class FeedbackMemoryAgent(BaseAgent):
    """
    Agentic Feedback Memory Agent
    - Stores knowledge gaps into persistent system_state.json
    - Uses gap_signal generated by KnowledgeGapAgent
    - Fully agentic-ready with evaluate/propose_action/execute
    """

    def __init__(self, state_path="system_state.json"):
        super().__init__(name="FeedbackMemoryAgent")
        self.state_path = state_path

    # -------------------
    # LEGACY METHODS
    # -------------------
    def can_handle(self, payload: Dict[str, Any]) -> bool:
        return (
            payload.get("gap_signal") is not None
            and not payload.get("_feedback_done", False)
        )

    def run(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        return self.execute(payload)

    # -------------------
    # AGENTIC METHODS
    # -------------------
    def evaluate(self, payload: Dict[str, Any]) -> bool:
        """
        Decide if FeedbackMemoryAgent should act
        """
        return self.can_handle(payload)

    def propose_action(self, payload: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        After feedback is logged, suggest ClaraAgent as next step
        """
        return {
            "next_agents": ["ClaraAgent"],
            "tools_to_call": [],
            "modify_payload": {}
        }

    def execute(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        gap_signal = payload.get("gap_signal")
        if not gap_signal:
            payload["_feedback_done"] = True
            return payload

        print("\n🧠 [FeedbackMemoryAgent] Logging knowledge gap...")

        query = payload.get("query")
        answer = payload.get("answer")  # may be None

        # 🔥 EXACT REQUIRED STRUCTURE
        gap_entry = {
            "question": query,
            "system_answer": answer.get("text") if answer else None,
            "gap_reason": gap_signal.get("reason"),
            "severity": gap_signal.get("severity"),
            "llm_analysis": gap_signal.get("llm_analysis", {})
        }

        # Update payload memory
        payload.setdefault("knowledge_gaps", [])
        payload["knowledge_gaps"].append(gap_entry)

        # Persist safely
        self._persist_to_system_state(payload["knowledge_gaps"])

        print("✅ Knowledge gap added to payload memory")

        # 🔥 CRITICAL: prevent loop
        payload["_feedback_done"] = True

        return payload

    # -------------------
    # Persistence
    # -------------------
    def _load_system_state(self) -> Dict[str, Any]:
        if not os.path.exists(self.state_path):
            return {"knowledge_gaps": [], "active_vector_source": "COSMOS"}

        try:
            with open(self.state_path, "r") as f:
                state = json.load(f)
            state.setdefault("knowledge_gaps", [])
            state.setdefault("active_vector_source", "COSMOS")
            return state
        except Exception:
            return {"knowledge_gaps": [], "active_vector_source": "COSMOS"}

    def _save_system_state(self, state: Dict[str, Any]):
        with open(self.state_path, "w") as f:
            json.dump(state, f, indent=2)

    def _persist_to_system_state(self, knowledge_gaps: list):
        state = self._load_system_state()
        state["knowledge_gaps"] = knowledge_gaps
        self._save_system_state(state)
        print("✅ Knowledge gaps persisted to system_state.json")
